# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Pulseq-CEST
url:              https://pulseq-cest.github.io/
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

github:
  matlab:           https://github.com/kherz/pulseq-cest
  python:           https://github.com/KerstinHut/pypulseq-cest
  library:          https://github.com/kherz/pulseq-cest-library
